#!/usr/bin/env bash

export DOTFILES_LOG="./dotfiles.log"

source ./lib/utils
source ./lib/setup

#before moving on, checking some dependencies
check_dependencies

#config ssh keys
setup_generate_ssh_keys

#execute all installation files
for f in scripts/*.sh;
	do
		bash "$f" -H || break
	done;

